# Tên ứng dụng
spring.application.name=distributed-booking

# Render sẽ tự cấp Port, dòng này giúp Spring nhận Port từ Render hoặc mặc định 8080 ở máy nhà
server.port=${PORT:8080}

# ID định danh của Server Dương (Dùng để hiển thị trên Dashboard)
server.id=Cloud-Server-Duong

# Danh sách link Render của 2 bạn (PEERS) - Cách nhau bằng dấu phẩy, KHÔNG CÓ khoảng trắng
# Lưu ý: Mình đã đưa link của Dương ra ngoài và chỉ để link 2 bạn vào mục Peer
peer.servers=https://dien-toan.onrender.com,https://flight-booking-distributed.onrender.com

# Tắt cache Thymeleaf để cập nhật giao diện nhanh hơn
spring.thymeleaf.cache=false

# Kết nối MongoDB Atlas (Giữ nguyên của Dương)
spring.data.mongodb.uri=mongodb+srv://dluu5032_db_user:Mvt7lR6jK0INhlo6@cluster0.rw2nn1s.mongodb.net/FlightDB?retryWrites=true&w=majority